// Job families researched on https://k72.ca/agence, 19 September 2026.
// Names are GRELLWERK identities. Examples describe this portfolio, not live agents.
const agents=[
 {id:'aura',name:'AURA',department:'Leitung',role:'Geschäftsführung',action:'Verantwortet Richtung und Prioritäten.',desc:'Klärt, was das Projekt erreichen soll, stellt das Team zusammen und entscheidet über Umfang und Freigabe.',input:'Ziel, Budgetrahmen, Termin',output:'Projektauftrag und besetztes Team',handoff:'LINK führt das Projekt weiter.',sample:'KOLD BREW',image:'kold',case:'kold-brew',example:'Auftrag: eine Cold-Brew-Marke mit Verpackung, Kampagne und digitalem Auftritt entwickeln. Ein gemeinsamer Leitgedanke für alle drei.'},
 {id:'link',name:'LINK',department:'Leitung',role:'Beratung & Projektleitung',action:'Macht Entscheidungen verbindlich.',desc:'Hält Briefing, Zeitplan und Rückmeldungen zusammen. Klärt Widersprüche, bevor das Team in die nächste Runde geht.',input:'Projektauftrag und Kundenfeedback',output:'Briefing, Meilensteine, Entscheidungsliste',handoff:'VECTOR schärft die strategische Aufgabe.',sample:'HAFERKRAFT',image:'hafer',case:'haferkraft',example:'Im Briefing stehen Regalwirkung und Alltagstauglichkeit. LINK trennt Verpackungsfragen von späteren Kampagnenideen und bündelt die Freigaben.'},
 {id:'relay',name:'RELAY',department:'Leitung',role:'Operations & New Business',action:'Sichert Kapazität und Ablauf.',desc:'Ordnet Anfragen ein, plant Ressourcen und bereitet Angebote vor. Hält Aufwand, Termine und Zuständigkeiten zusammen.',input:'Anfrage, Leistungsumfang, Kapazität',output:'Projektumfang und Ressourcenplan',handoff:'AURA entscheidet, LINK übernimmt.',sample:'BLITZBANK',image:'blitz',case:'blitzbank',example:'Für die Markenstudie werden Strategie, Gestaltung und Digital getrennt geplant. Zusätzliche Motive bekommen einen eigenen Aufwand statt still in den Auftrag zu rutschen.'},
 {id:'vector',name:'VECTOR',department:'Strategie',role:'Strategie',action:'Findet den Grund für die Gestaltung.',desc:'Untersucht Zielgruppe, Wettbewerb und Positionierung. Formuliert die Frage, die die kreative Arbeit beantworten muss.',input:'Briefing und Recherche',output:'Positionierung und Kreativbriefing',handoff:'PROMPT entwickelt die Leitidee.',sample:'HAFERKRAFT',image:'hafer-detail',case:'haferkraft',example:'Wie fällt ein Haferdrink zwischen ähnlichen Packungen auf? Deutliche Schrift, sichtbarer Hafer und eine Sprache, die zum alltäglichen Morgen passt.'},
 {id:'metric',name:'METRIC',department:'Strategie',role:'Analyse & Wirkung',action:'Definiert, woran wir Arbeit messen.',desc:'Formuliert Testfragen und wertet Ergebnisse aus, sobald Daten vorliegen. Kennzeichnet Annahmen und leitet daraus den nächsten Versuch ab.',input:'Ziele, Varianten und Messdaten',output:'Messplan und begründete Empfehlung',handoff:'LINK priorisiert die nächste Iteration.',sample:'NEONTRITT',image:'neon-detail',case:'neontritt',example:'Testfrage: Führt das Produktmotiv oder die Szene auf der Straße häufiger zum Projekt? Verglichen würden Aufrufe je Besuch. Hier liegen noch keine Kampagnendaten vor.'},
 {id:'prompt',name:'PROMPT',department:'Kreation',role:'Creative Direction',action:'Hält die kreative Idee zusammen.',desc:'Entwickelt das Konzept und beurteilt Text und Gestaltung im Zusammenhang. Entscheidet, welche Richtung weiter ausgearbeitet wird.',input:'Kreativbriefing',output:'Leitidee und kreative Richtung',handoff:'VOICE und VISUAL arbeiten sie aus.',sample:'KOLD BREW',image:'kold',case:'kold-brew',example:'„Deine Nacht. Deine Krone.“ verbindet die schwarze Dose, die handgemalte Krone und den rauen Schriftzug zu einer Kampagne.'},
 {id:'voice',name:'VOICE',department:'Kreation',role:'Konzept & Text',action:'Schreibt die Worte, die bleiben.',desc:'Entwickelt Headlines, Markenstimme und Kampagnentexte. Prüft, ob eine Aussage zur Marke gehört und sich tatsächlich belegen lässt.',input:'Leitidee und Produktinformationen',output:'Headlines, Copy und Tonalität',handoff:'VISUAL setzt Wort und Bild zusammen.',sample:'KOLD BREW',image:'kold-detail',case:'kold-brew',example:'Aus einer langen Produktbeschreibung wird die Kampagnenzeile „Deine Nacht. Deine Krone.“. Produktinformationen bleiben auf der Verpackung.'},
 {id:'visual',name:'VISUAL',department:'Kreation',role:'Art Direction',action:'Bestimmt Bild, Schrift und Material.',desc:'Entwickelt die visuelle Sprache und inszeniert die Motive. Beurteilt eine Serie als Ganzes, vom ersten Plakat bis zum kleinsten Format.',input:'Konzept, Copy und Bildreferenzen',output:'Bildwelt und Gestaltungsprinzipien',handoff:'GRID baut das Gestaltungssystem.',sample:'NEONTRITT',image:'neon',case:'neontritt',example:'Schwarzes Mesh, helle Besätze, Limettensohle. Licht, Material und Perspektive bleiben in Produktmotiv und Straßenszene wiedererkennbar.'},
 {id:'grid',name:'GRID',department:'Kreation',role:'Design & Reinzeichnung',action:'Bringt die Idee in jedes Format.',desc:'Überführt die Art Direction in Layouts, Regeln und saubere Dateien. Achtet auf Typografie, Raster, Abstände und Lesbarkeit.',input:'Freigegebene Art Direction',output:'Layouts, Varianten und Produktionsdateien',handoff:'SYNTAX übernimmt die digitale Umsetzung.',sample:'HAFERKRAFT',image:'hafer',case:'haferkraft',example:'Die große Wortmarke, der grüne Verschluss und das Hafermotiv bilden ein System für beide Packungsgrößen. Die Hierarchie bleibt gleich.'},
 {id:'syntax',name:'SYNTAX',department:'Produktion',role:'Digital Development',action:'Baut eine Seite, die sich bedienen lässt.',desc:'Setzt Layout und Interaktionen um. Plant Navigation, mobile Ansichten, Tastaturbedienung und Ladeverhalten zusammen.',input:'Layouts und Interaktionskonzept',output:'Funktionierende digitale Strecke',handoff:'CUT prüft die Gestaltung, VERIFY die Funktion.',sample:'BLITZBANK',image:'blitz-detail',case:'blitzbank',example:'Die Projektübersicht führt direkt zur Markenstudie. Zurück, Vorwärts und direkte Seitenaufrufe bleiben Teil derselben Strecke.'},
 {id:'cut',name:'CUT',department:'Produktion',role:'Designkritik · KI-Entshitifier',action:'Streicht, was nur nach Gestaltung aussieht.',desc:'Prüft jede Fläche, jeden Effekt und jeden Satz auf eine Aufgabe. Stoppt austauschbare Karten, dekorative Daueranimation und erfundene Belege.',input:'Entwurf und gerenderte Seite',output:'Konkrete Streichliste mit Begründung',handoff:'VISUAL und SYNTAX korrigieren; VERIFY prüft danach.',sample:'KOLD BREW',image:'kold',case:'kold-brew',example:'Ein Hauptmotiv, eine Krone, eine Textbotschaft. Zusätzliche Badges oder ein zweiter Slogan würden hier die Hierarchie verwässern. CUT benennt, was dafür entfallen muss.'},
 {id:'verify',name:'VERIFY',department:'Produktion',role:'Quality Assurance',action:'Prüft die Umsetzung bis zum letzten Link.',desc:'Testet Funktion, Darstellung und Zugänglichkeit. Meldet Fehler mit nachvollziehbaren Schritten und unterscheidet technische Prüfung von Designfreigabe.',input:'Umgesetzte Seite und Prüfplan',output:'Fehlerbericht und geprüfte Korrekturen',handoff:'AURA verantwortet die Freigabe.',sample:'BLITZBANK',image:'blitz',case:'blitzbank',example:'Prüfpunkte: schmale Displays, Tastatur, schnelle Klicks, Browserhistorie, fehlende Bilder und abgeschaltete Bewegung.'}
];
module.exports={agents};
