const {renderAgencyOpening,renderCrewFeatures}=require('./direction.cjs');
const {agents}=require('./agency.cjs');
const {renderAgencyStory}=require('./agency-story.cjs');
const departments=['Leitung','Strategie','Kreation','Produktion'];
const number=i=>String(i+1).padStart(2,'0');
function profile(a,mobile=false){return `<figure class="agent-portrait"><img src="assets/agents/${a.id}-1080.webp" srcset="assets/agents/${a.id}-600.webp 600w, assets/agents/${a.id}-1080.webp 1080w" sizes="(max-width:700px) 100vw, 40vw" width="1080" height="1440" alt="${a.name}: fiktive KI-Persona, mit sichtbaren synthetischen Bauteilen an Schläfe und Hals" loading="eager" decoding="async"><figcaption>KI-PERSONA / ${a.name}</figcaption></figure><div class="profile-copy"><div class="profile-head"><div><p>${a.role}</p><h3>${a.name}</h3></div></div><p class="profile-mandate">${a.action}</p><p class="profile-description">${a.desc}</p><details class="profile-more"><summary>Auftrag &amp; Arbeitsbeispiel <span>＋</span></summary><div><p class="profile-example">${a.example}</p><dl class="profile-delivery"><div><dt>Übernimmt</dt><dd>${a.input}</dd></div><div><dt>Liefert</dt><dd>${a.output}</dd></div></dl><p class="profile-handoff">${a.handoff}</p><a class="profile-project" href="case-${a.case}.html">${a.sample} ansehen <span>↗</span></a></div></details></div>`;}
function renderAgency(specialists){return `
<nav class="chapter-nav" data-chapter-nav aria-label="Studio entdecken"><a data-chapter-link href="#zusammenarbeit">Arbeitsweise</a><a data-chapter-link href="#crew">Die Crew</a><a data-chapter-link href="#designpruefung">Designprüfung</a></nav>
${renderAgencyOpening()}
${renderAgencyStory()}
${renderCrewFeatures()}
<section class="agency-team" id="crew" aria-labelledby="team-title"><div class="team-heading"><h2 id="team-title">DIE CREW.<sup>${agents.length}</sup></h2><p>Zwölf fiktive KI-Personas. Wähle einen Kopf und lerne seine Aufgabe kennen.</p></div><div class="team-filters" aria-label="Team nach Bereich filtern"><button type="button" data-team-filter="all" aria-pressed="true">Alle ${agents.length}</button>${departments.map(d=>`<button type="button" data-team-filter="${d}" aria-pressed="false">${d}</button>`).join('')}</div>
<div class="team-layout"><div class="team-index" aria-label="Agent auswählen">${agents.map((a,i)=>`<button type="button" data-agent="${a.id}" data-department="${a.department}" aria-pressed="${i===0}" aria-controls="agent-${a.id}"><span class="team-number">${number(i)}</span><span class="team-name">${a.name}<small>${a.role}</small></span><span class="team-arrow">↗</span></button>`).join('')}</div><div class="team-profile">${agents.map((a,i)=>`<article class="agent-panel" id="agent-${a.id}" ${i?'hidden':''}>${profile(a)}</article>`).join('')}</div></div>
<div class="team-mobile">${agents.map((a,i)=>`<details data-agent-mobile="${a.id}" data-department="${a.department}" ${i===0?'open':''}><summary><span>${number(i)}</span><span>${a.name}<small>${a.role}</small></span><span>＋</span></summary><div>${profile(a,true)}</div></details>`).join('')}</div></section>

<section class="cut-workshop" id="designpruefung" aria-labelledby="cut-title"><div class="cut-workshop-copy"><span>CUT / EIN EINGRIFF</span><h2 id="cut-title">WENIGER DRAUF.<br>MEHR DAHINTER.</h2><p>Drei Zusatzbotschaften konkurrieren mit der Kampagnenidee. CUT entfernt sie. Probiere den Vorher-nachher-Wechsel.</p></div><div class="cut-proof"><div class="cut-image"><img src="assets/campaigns/kold-detail-v2-800.webp" width="800" height="533" alt="KOLD BREW Plakatentwurf mit zuschaltbaren Zusatzbotschaften" loading="lazy"><span class="cut-extra extra-one">100%<br>PREMIUM</span><span class="cut-extra extra-two">DEIN NEUES<br>LIEBLINGSGETRÄNK</span><span class="cut-extra extra-three">JETZT ENTDECKEN!</span><h2>DEINE NACHT.<br>DEINE KRONE.</h2></div><div class="cut-controls"><span data-cut-status role="status" aria-live="polite">BEISPIELENTWURF / VORHER</span><button data-cut-toggle aria-pressed="false">CUT anwenden ↗</button></div></div></section>
<section class="specialists agency-specialists" id="spezialisten"><h2>FÜR DIE DETAILS.</h2><p>Weitere Spezialisierungen ergänzen das Kernteam.</p>${specialists.map(([group,list])=>`<details><summary>${group}<span>${list.length} Spezialisten ＋</span></summary><div class="specialist-list">${list.map(([n,r])=>`<div><h3>${n}</h3><p>${r}</p></div>`).join('')}</div></details>`).join('')}<p class="fiction-note">GRELLWERK ist ein Agenturkonzept mit KI-Rollen. Alle Porträts zeigen KI-generierte, fiktive Personen. Die Kampagnen sind freie Arbeiten. Auf dieser Website laufen keine autonomen Agenten im Hintergrund.</p></section>`;}
module.exports={renderAgency};
