const {loop}=require('./motion.cjs');
const steps=[
 {id:'brief',label:'Das Briefing',person:'vector',name:'VECTOR',role:'Strategie',title:'Für wen bleiben<br>wir wach?',copy:'Cold Brew für die Stunden nach Feierabend. VECTOR macht aus der ersten Idee eine Aufgabe, mit der die Kreation weiterarbeiten kann.',from:'Menschen, deren Abend gerade anfängt.',to:'Die Nacht als gemeinsamer Nenner.'},
 {id:'idea',label:'Die Gestaltung',person:'prompt',name:'PROMPT',role:'Creative Direction',title:'Die Nacht.<br>Die Krone.',copy:'PROMPT entwickelt die Leitidee. VOICE gibt ihr Worte, VISUAL die Bildwelt. GRID verbindet Dose, Plakat und Website.',from:'Eine gelbe Krone auf tiefem Schwarz.',to:'Deine Nacht. Deine Krone.'},
 {id:'result',label:'Das Ergebnis',person:'syntax',name:'SYNTAX',role:'Digital Development',title:'Die Idee<br>wird bedienbar.',copy:'SYNTAX baut die digitale Strecke. CUT hinterfragt die Gestaltung, VERIFY prüft die Bedienung. Menschen entscheiden, was veröffentlicht wird.'}
];
const art={brief:`<div class="brief-sheet"><span>KOLD BREW / Kreativbriefing</span><strong>KALT GEBRAUT.<br>HELLWACH<br>GEDACHT.</strong><p>Eine schwarze Dose.<br>Ein Zeichen für die Nacht.<br>Eine Sprache, die direkt ist.</p><span>Übergabe an PROMPT ↗</span></div>`,idea:`<figure class="handoff-art"><img src="assets/campaigns/kold-v2-1536.webp" srcset="assets/campaigns/kold-v2-800.webp 800w, assets/campaigns/kold-v2-1536.webp 1536w" sizes="(max-width:700px) 100vw, 60vw" width="1536" height="1024" alt="KOLD BREW Verpackungsstudie mit schwarzer Dose und gelber Krone" loading="lazy"><figcaption>IDENTITÄT / PACKAGING / FREIE STUDIE</figcaption></figure>`,result:`<a class="agency-story-film" href="case-kold-brew.html" aria-label="KOLD BREW: Das Ergebnis ansehen">${loop('coffee')}<span>DEINE NACHT.<br>DEINE KRONE. ↗</span></a>`};
function renderAgencyStory(){return `<section class="agency-story handoff-studio" id="zusammenarbeit" aria-labelledby="handoff-title"><div class="handoff-heading"><div><span class="eyebrow">Eine Marke entsteht / KOLD BREW</span><h2 id="handoff-title" data-reveal>VON KOPF<br>ZU KOPF.</h2></div><p>Ein Briefing wird zur Idee. Die Idee bekommt eine Form. Wähle einen Schritt und sieh dir an, was die nächste Rolle übernimmt.</p></div><div class="handoff-tabs" role="tablist" aria-label="Schritte der Zusammenarbeit">${steps.map((s,i)=>`<button role="tab" id="step-${s.id}" aria-controls="handoff-${s.id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-handoff="${s.id}"><span>0${i+1}</span>${s.label}<b aria-hidden="true">↗</b></button>`).join('')}</div><div class="handoff-stage">${steps.map((s,i)=>`<div role="tabpanel" id="handoff-${s.id}" aria-labelledby="step-${s.id}" tabindex="0" class="handoff-panel" ${i?'hidden':''}><div class="handoff-note"><a class="handoff-person" href="ueber-uns.html?agent=${s.person}#crew"><img src="assets/agents/${s.person}-600.webp" width="600" height="800" alt="${s.name}, fiktive KI-Persona" loading="lazy"><span>${s.name}<small>${s.role} ↗</small></span></a><h3>${s.title}</h3><p>${s.copy}</p>${s.from?`<dl><div><dt>Übernimmt</dt><dd>${s.from}</dd></div><div><dt>Gibt weiter</dt><dd>${s.to}</dd></div></dl>`:'<a class="editorial-link" href="case-kold-brew.html">Den ganzen Case ansehen ↗</a><button class="handoff-pause" type="button" data-reel-toggle aria-pressed="false">Bewegung pausieren</button>'}</div>${art[s.id]}</div>`).join('')}</div><p class="handoff-caption">Ein vorbereitetes Arbeitsbeispiel aus unserem fiktiven Agenturkonzept.</p></section>`;}
module.exports={renderAgencyStory};
