const studioPhoto=(cls='',priority=false)=>`<img class="${cls}" src="assets/studio/worktable-1536.webp" srcset="assets/studio/worktable-800.webp 800w, assets/studio/worktable-1536.webp 1536w" sizes="(max-width:700px) 100vw, 60vw" width="1536" height="1024" alt="KI-generierte Studiostudie: Verpackungen, Papier und ein Entwurf auf dem Arbeitstisch" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
function serviceOpening(){return `<section class="opening-service experience-opening"><div class="service-direction"><p class="eyebrow">Leistungen / Strategie · Kreation · Digital</p><h1 data-enter>WAS WIR<br>DARAUS MACHEN.</h1><nav class="discipline-index" aria-label="Leistungseinstiege"><a href="leistung-brand.html"><span>Marken</span><span>Eine eigene Sprache.<br>In Wort und Bild.</span><b aria-hidden="true">↗</b></a><a href="leistung-kampagnen.html"><span>Kampagnen</span><span>Eine Idee, die sich<br>weitererzählen lässt.</span><b aria-hidden="true">↗</b></a><a href="leistung-web.html"><span>Digitale Erlebnisse</span><span>Vom ersten Eindruck<br>zum nächsten Klick.</span><b aria-hidden="true">↗</b></a></nav></div><figure class="service-still" data-enter>${studioPhoto('',true)}<figcaption>GRELLWERK / Freie Materialstudie</figcaption></figure><div class="opening-bottom"><p>Von der ersten Idee bis zum letzten Detail.</p><a class="editorial-link" href="#leistungen-all">Alle sechs Disziplinen ↘</a></div></section>`;}
function journalOpening(){return `<section class="opening-journal experience-opening"><p class="eyebrow">Journal / Aus der Werkstatt</p><h1 data-enter>GEDANKEN,<br>DIE WEITERGEHEN.</h1><a class="journal-feature" href="journal-prompt-orchestrierung.html"><figure data-enter>${studioPhoto('',true)}<figcaption>KI &amp; Kreation / Ein Blick auf die Arbeit dahinter</figcaption></figure><div><span class="eyebrow">Ausgewählter Artikel</span><h2>Dein KI-Output ist so gut wie dein schlechtester Prompt</h2><p>Über Briefings, Zusammenarbeit und die Entscheidungen vor dem Ergebnis.</p><span class="editorial-link">Artikel lesen ↗</span></div></a></section>`;}
function renderLab(raw){
 const sections=[...raw.matchAll(/<section\b[\s\S]*?<\/section>/g)].map(m=>m[0]);
 const slogan=sections.find(s=>s.includes('id="slogan-lab"'));
 const form=slogan.match(/<form\b[\s\S]*?<\/form>/)[0].replace('Krach erzeugen ⚡','Krach erzeugen ↗').replace('placeholder="z. B. Haferkraft"','placeholder="z. B. NEONTRITT"').replace(/data-ton="([^"]+)"/g,(_,tone)=>`data-ton="${tone}" aria-pressed="${tone==='frech'}"`);
 return `<section class="play-opening experience-opening" id="slogan-lab"><div class="play-direction"><p class="eyebrow">Spielwiese / Lokales Wortspiel</p><h1 data-enter>MACH MAL<br>KRACH.</h1><p>Ein Gedanke. Drei Richtungen.</p><p class="play-explainer">Deine Marke, deine Tonlage. Das Wortspiel kombiniert lokale Textbausteine zu drei Ideen.</p><a class="editorial-link" href="#konfigurator">Was braucht deine Marke? ↘</a></div><div class="play-machine" data-enter>${form}<div class="slogan__out" id="slogan-out" aria-live="polite"><div class="play-preview"><img src="assets/campaigns/neon-detail-v2-800.webp" width="800" height="533" alt="NEONTRITT Sneaker aus unserer freien Markenstudie"><p>HINTERLASS<br>EINEN EINDRUCK.</p><small>Beispiel / NEONTRITT</small></div></div><p class="play-note">Läuft in deinem Browser. Keine Anfrage an eine KI.</p></div></section>${sections.filter(s=>!s.includes('id="slogan-lab"')).sort((a,b)=>{const order=s=>s.includes('id="konfigurator"')?0:s.includes('id="pakete"')?1:2;return order(a)-order(b);}).join('\n')}`;
}
module.exports={studioPhoto,serviceOpening,journalOpening,renderLab};
