const {projects,agents}=require('./site.cjs');
const {loop,motion}=require('./motion.cjs');
const backgrounds={kold:'kold-street-v4',neon:'neon-detail-v2',hafer:'hafer-detail-v2',blitz:'blitz-scene-v12'};
const context={kold:'Eine Krone für die Nacht.',neon:'Für draußen gemacht.',hafer:'Ein guter Morgen fängt klein an.',blitz:'Ein Zeichen. Ein Standpunkt.'};
const nl=s=>s.replace(/\n/g,'<br>');
const sceneAlts={kold:'Eine Hand hält die schwarze KOLD BREW Dose am nächtlichen Kiosktresen',neon:'NEONTRITT Sneaker mit Limettensohle in einem Schritt auf nassem Asphalt',hafer:'HAFERKRAFT Packung neben einer Kaffeetasse in einer hellen Morgenküche',blitz:'Eine Hand hält die schwarze BLITZBANK Konzeptkarte vor ruhigem Architekturbeton'};
function visual(p,{detail=false,scene=false,life=false,priority=false,sizes='100vw'}={}){
 const file=life?p.id+'-scene-v12':scene?backgrounds[p.id]:p.id+(detail?'-detail-v2':'-v2');
 const alt=life||file.endsWith('-scene-v12')?sceneAlts[p.id]:scene&&p.id==='kold'?'KOLD BREW Kampagne: schwarze Dose, gelbe Krone und ein nächtlicher Kiosk':detail?p.detailAlt:p.alt;
 return `<div class="campaign-image" data-image-label="${p.name}">${scene&&p.id==='kold'?'<picture><source media="(max-width:700px), (max-width:1000px) and (orientation:portrait)" srcset="assets/campaigns/kold-street-v4-mobile.webp">':''}<img src="assets/campaigns/${file}-1536.webp" srcset="assets/campaigns/${file}-800.webp 800w, assets/campaigns/${file}-1536.webp 1536w" sizes="${sizes}" width="1536" height="${scene&&p.id==='kold'?864:1024}" alt="${alt}" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async">${scene&&p.id==='kold'?'</picture>':''}</div>`;
}
function renderHome(){return `<section class="screening-room" aria-label="GRELLWERK Kampagnen">
 <div class="screen-media">${projects.map((p,i)=>`<div class="screen-frame ${i?'':'is-active'}" data-screen="${i}" ${i?'aria-hidden="true"':''}>${visual(p,{scene:true,priority:i===0})}</div>`).join('')}</div>
 <div class="screen-shade" aria-hidden="true"></div>
 <div class="screen-intro"><p>Independent creative studio</p><h1><span>GUTE IDEEN.</span><span>SCHLECHTE</span><span>RUHE.</span></h1></div>
 <div class="screen-bottom"><div class="screen-selector" aria-label="Kampagne auswählen">${projects.map((p,i)=>`<button type="button" data-screen-select="${i}" aria-pressed="${i===0}" aria-label="${p.name} im Vollbild zeigen"><span>0${i+1}</span><span>${p.name}</span></button>`).join('')}</div>
 <div class="screen-route"><a class="screen-case" data-screen-link href="case-kold-brew.html">KOLD BREW entdecken <span>↗</span></a><a href="arbeiten.html" class="screen-all">Alle Projekte <span>↗</span></a></div></div>
 <p class="sr-only" data-screen-status aria-live="polite">KOLD BREW ausgewählt</p>
 </section>`;}
function renderProjects(){return `<section class="work-title"><h1>PROJEKTE<sup>04</sup></h1><div class="work-intro"><p>Vier Marken. Vier eigene Welten.</p><a href="ueber-uns.html">Das Studio dahinter ↗</a></div></section>
 <section class="work-gallery" aria-label="Unsere Projekte">${projects.map((p,i)=>`<article class="work-item" data-reveal><a href="case-${p.slug}.html" class="work-image-link" aria-label="${p.name}: Projekt ansehen">${visual(p,{scene:i===0,priority:i<2})}<span class="work-enter" aria-hidden="true">Ansehen ↗</span></a><div class="work-caption"><div><span class="work-id">0${i+1}</span><h2><a href="case-${p.slug}.html">${p.name}</a></h2></div><p>${context[p.id]}</p><span>${p.discipline}</span></div></article>`).join('')}<p class="fiction-note">Freie Konzeptarbeiten. Marken, Produkte und Kampagnen sind fiktiv.</p></section>`;}
function renderCase(p,i){const next=projects[(i+1)%projects.length];return `<section class="case-opening"><div class="case-opening-media">${visual(p,{scene:true,priority:true})}</div><div class="case-opening-shade"></div><a class="case-back" href="arbeiten.html#projekt-${p.id}">← Alle Projekte</a><div class="case-opening-title"><p>${p.discipline}</p><h1>${p.name}</h1><span>${context[p.id]}</span></div></section>
 <nav class="case-chapters chapter-nav" data-chapter-nav aria-label="Projektkapitel"><a data-chapter-link href="#idee">Die Idee</a><a data-chapter-link href="#gestaltung">Die Gestaltung</a><a data-chapter-link href="#team">Die Crew</a></nav>
 <section class="case-narrative" id="idee"><div><p>Die Idee</p><h2>${nl(p.line)}</h2></div><p>${p.intro}</p><div class="case-facts"><div><h3>Die Aufgabe</h3><p>${p.brief}</p></div><div><h3>Der Gedanke</h3><p>${p.idea}</p></div><div><h3>Die Umsetzung</h3><p>${p.output}</p></div></div></section>
${motion[p.id]?`<section class="case-motion" style="--project-accent:${p.color}" aria-label="${p.name}: Bewegungsstudie"><div class="case-motion-film">${loop(motion[p.id])}<div class="work-screen-shade"></div><p>${nl(p.poster)}</p></div><div class="case-motion-caption"><span>${p.name} / Bewegungsstudie</span><button type="button" data-reel-toggle aria-pressed="false">Bewegung pausieren</button></div></section>`:''}
 <section class="case-gallery-v4" id="gestaltung" aria-label="Kampagnenmotive"><figure class="case-life" data-reveal>${visual(p,{life:true})}<figcaption>01 / ${p.name} im Alltag</figcaption></figure><figure class="case-product" data-reveal>${visual(p,{sizes:'(max-width:700px) 100vw, 46vw'})}<figcaption>02 / Die Marke</figcaption></figure><figure class="case-detail" data-reveal>${visual(p,{detail:true,sizes:'(max-width:700px) 100vw, 46vw'})}<figcaption>03 / Im Detail</figcaption></figure><div class="case-type-poster" style="--poster-color:${p.color}" data-reveal><p>${nl(p.poster)}</p><span>${p.name}®</span></div></section>
 <section class="case-team-v4" id="team"><h2>DAHINTER<br>STECKT TEAM.</h2><nav aria-label="Beteiligte Agenten">${['prompt','visual','voice','grid','syntax','cut','verify'].map(id=>{const a=agents.find(a=>a.id===id);return `<a href="ueber-uns.html?agent=${id}#crew"><strong>${a.name}</strong><span>${a.role}</span><span>↗</span></a>`;}).join('')}</nav><p class="fiction-note">Freie Konzeptarbeit · ${p.year} · Keine echte Kundenkampagne.</p></section>
 <nav class="case-exit" aria-label="Weiter entdecken"><a href="arbeiten.html#projekt-${p.id}">Alle Projekte ↗</a><a href="ueber-uns.html#crew">Crew kennenlernen ↗</a><a href="kontakt.html?project=${p.slug}">Briefing vorbereiten ↗</a></nav>
 <a class="next-screen" href="case-${next.slug}.html">${visual(next,{scene:true})}<span>Nächstes Projekt</span><strong>${next.name} ↗</strong></a>`;}
module.exports={renderHome,renderProjects,renderCase,visual};
