const projects = [
 {id:'kold',slug:'kold-brew',name:'KOLD BREW',line:'Kalt gebraut.\nHellwach gedacht.',discipline:'Branding · Campaign · Digital',color:'#d6ff3b',year:'2026',intro:'Kaffee für die Stunden, in denen andere schon Schluss machen. Eine Marke zwischen nächtlichem Kiosk, kaltem Asphalt und dem ersten guten Gedanken.',brief:'Cold Brew aus der Nische holen. Ohne Barista-Erklärstunde, dafür mit einer klaren Haltung und einer Dose, die auch aus fünf Metern noch auffällt.',idea:'Schwarz wie die Nacht. Eine gelbe Krone. Zwei Wörter, die auf der Dose genauso sitzen wie auf einer Häuserwand. KOLD BREW macht Wachsein zum gemeinsamen Nenner.',output:'Identität, Packaging, Kampagnenmotive und eine digitale Launch-Strecke. Als zusammenhängendes Markenkonzept entwickelt.',poster:'DEINE NACHT.\nDEINE KRONE.',alt:'Zwei schwarze KOLD BREW Dosen mit gelber Krone auf Eis und Kaffeebohnen',detailAlt:'Nahaufnahme der schwarzen KOLD BREW Dose mit gelber Krone, Wassertropfen und Eis'},
 {id:'neon',slug:'neontritt',name:'NEONTRITT',line:'Die Straße\nist dein Laufsteg.',discipline:'Art Direction · Brand · Campaign',color:'#bcff39',year:'2026',intro:'Ein Sneaker mit Straßeninstinkt. Schwarz hält sich zurück. Die Sohle übernimmt den Rest.',brief:'Eine neue Sneakermarke braucht einen wiedererkennbaren Auftritt. Nicht noch ein Schuh vor einem farbigen Hintergrund, sondern ein Gefühl für Bewegung in der Stadt.',idea:'Neongrün wird zum Abdruck. Auf nassem Asphalt, auf Plakaten, im Feed. Die Bildwelt bleibt roh; das Produkt ist bis zur letzten Naht präzise.',output:'Visuelle Identität, Produktinszenierung, Launch-Kampagne und digitale Motive. Eine freie Studie für eine erfundene Streetwear-Marke.',poster:'HINTERLASS\nEINEN EINDRUCK.',alt:'NEONTRITT Sneaker mit schwarzem Mesh, hellen Besätzen und Limettensohle',detailAlt:'NEONTRITT Sneaker auf nassem Asphalt bei Nacht'},
 {id:'hafer',slug:'haferkraft',name:'HAFERKRAFT',line:'Kleine Körner.\nGroßer Morgen.',discipline:'Strategy · Packaging · Campaign',color:'#c1cbb7',year:'2026',intro:'Haferdrink für den ganz normalen Morgen. Ehrliche Materialien, deutliche Schrift und eine Portion trockener Humor.',brief:'Im Regal stehen viele beigefarbene Versprechen. HAFERKRAFT soll vertraut wirken und trotzdem eine eigene Stimme haben.',idea:'Wir geben dem Hafer Platz. Auf der Verpackung, im Bild und in der Sprache. Große schwarze Buchstaben treffen auf grüne Details und ruhige, warme Stillleben.',output:'Markenidee, Verpackungssystem und eine Kampagne rund um den ersten Kaffee. Alle Motive gehören zu einer fiktiven Produktstudie.',poster:'MORGEN\nWIRD GUT.',alt:'HAFERKRAFT Haferdrink-Verpackungen mit Hafer auf einer hellen Steinfläche',detailAlt:'HAFERKRAFT Haferdrink neben einer Kaffeetasse im Morgenlicht'},
 {id:'blitz',slug:'blitzbank',name:'BLITZBANK',line:'Geld ist ernst.\nBanking muss es nicht sein.',discipline:'Positioning · Identity · Digital',color:'#d6ff3b',year:'2026',intro:'Eine Bankmarke, die ihre Sätze zu Ende bringt. Kurze Worte, ein scharfes Zeichen und ein Auftritt, der auf der Straße funktioniert.',brief:'Finanzkommunikation klingt oft nach Kleingedrucktem. Wie sieht eine Marke aus, die Orientierung gibt und dabei im Kopf bleibt?',idea:'Der Blitz wird zum Satzzeichen. Schwarz und Limette tragen die Identität vom Kartenformat bis zur Plakatwand. Das Raster hält alles zusammen.',output:'Positionierung, visuelles System, Kartenkonzept und Außenwerbung. Fiktive Markenstudie, kein echtes Finanzprodukt.',poster:'MEHR LOS.\nWENIGER BLA.',alt:'Schwarzer BLITZBANK Schriftzug und gelber Blitz direkt auf rauem Beton',detailAlt:'Eine schwarze und eine limettengrüne BLITZBANK Karte als Produktinszenierung'}
];
const {agents}=require('./agency.cjs');
const specialists = [
 ['Strategie', [['SPY','Wettbewerb verstehen'],['MODEL','Mediamix planen'],['TARGET','Zielgruppen schärfen'],['SURVEY','Stimmungen einordnen'],['SCOUT','Creator recherchieren']]],
 ['Kreation',[['HOOK','Video-Einstiege finden'],['MOTION','Bewegung entwerfen'],['BRIEF','Konzepte ausarbeiten']]],
 ['Technik',[['FRONT','Oberflächen umsetzen'],['SPEED','Ladezeiten verbessern'],['WATCHDOG','Verfügbarkeit prüfen'],['FORM','Formulare verbinden'],['COMPLY','Vorgaben abgleichen']]],
 ['Performance',[['META','Social-Kampagnen planen'],['SEARCH','Suchkampagnen strukturieren'],['NUDGE','Mailing-Strecken entwickeln'],['CRO','Varianten vergleichen'],['FINANCE','Budgets einordnen']]]
];
module.exports={projects,agents,specialists};
